-- MySQL 8+ views. Campaign figures are descriptive, not causal uplift or ROI.
USE pharma_sales_marketing_synthetic;
DROP VIEW IF EXISTS v_product_performance; DROP VIEW IF EXISTS v_campaign_performance; DROP VIEW IF EXISTS v_physician_segments; DROP VIEW IF EXISTS v_territory_performance; DROP VIEW IF EXISTS v_monthly_performance;
CREATE VIEW v_monthly_performance AS
WITH totals AS (SELECT f.month_start,p.territory_id,t.territory_name,COUNT(DISTINCT f.physician_id) physician_months,SUM(f.prescriptions) prescriptions,ROUND(SUM(f.revenue_usd),2) revenue_usd,COUNT(DISTINCT CASE WHEN f.prescriptions>0 THEN f.physician_id END) active_physicians FROM prescription_month f JOIN physician p ON p.physician_id=f.physician_id JOIN territory t ON t.territory_id=p.territory_id GROUP BY f.month_start,p.territory_id,t.territory_name), history AS (SELECT totals.*,LAG(prescriptions) OVER(PARTITION BY territory_id ORDER BY month_start) previous_month_rx FROM totals) SELECT history.*,ROUND(100.0*(prescriptions-previous_month_rx)/NULLIF(previous_month_rx,0),2) rx_growth_pct FROM history;
CREATE VIEW v_territory_performance AS SELECT p.territory_id,t.territory_name,COUNT(DISTINCT p.physician_id) physicians,SUM(f.prescriptions) prescriptions,ROUND(SUM(f.revenue_usd),2) revenue_usd,ROUND(SUM(f.prescriptions)/COUNT(DISTINCT p.physician_id),2) rx_per_physician,SUM(f.target_rx) target_rx,ROUND(100.0*SUM(f.prescriptions)/NULLIF(SUM(f.target_rx),0),2) target_attainment_pct,RANK() OVER(ORDER BY SUM(f.revenue_usd) DESC) revenue_rank,ROUND(100.0*SUM(f.revenue_usd)/SUM(SUM(f.revenue_usd)) OVER(),2) revenue_contribution_pct FROM prescription_month f JOIN physician p ON p.physician_id=f.physician_id JOIN territory t ON t.territory_id=p.territory_id GROUP BY p.territory_id,t.territory_name;
CREATE VIEW v_physician_segments AS WITH profile AS (SELECT p.physician_id,p.territory_id,p.specialty,SUM(f.prescriptions) annual_rx,SUM(f.prescriptions>0) active_months,COALESCE(MIN(CASE WHEN f.prescriptions>0 THEN 12-MONTH(f.month_start) END),12) months_since_activity FROM physician p JOIN prescription_month f ON f.physician_id=p.physician_id GROUP BY p.physician_id,p.territory_id,p.specialty), ranked AS (SELECT profile.*,NTILE(4) OVER(ORDER BY annual_rx,physician_id) volume_quartile FROM profile) SELECT ranked.*,CASE WHEN months_since_activity>=3 THEN 'Lapsed' WHEN volume_quartile=4 AND active_months>=9 THEN 'High activity' WHEN volume_quartile>=3 THEN 'Established' ELSE 'Low activity' END segment FROM ranked;
CREATE VIEW v_campaign_performance AS SELECT c.campaign_id,c.campaign_name,c.channel,COUNT(*) contacts,SUM(o.responded) responses,ROUND(100.0*SUM(o.responded)/NULLIF(COUNT(*),0),2) response_rate_pct,ROUND(SUM(o.cost_usd),2) contact_cost_usd,ROUND(SUM(o.cost_usd)/NULLIF(SUM(o.responded),0),2) cost_per_response_usd FROM outreach o JOIN campaign c ON c.campaign_id=o.campaign_id GROUP BY c.campaign_id,c.campaign_name,c.channel;
CREATE VIEW v_product_performance AS SELECT p.product_id,p.product_name,p.therapy_area,SUM(f.prescriptions) prescriptions,ROUND(SUM(f.revenue_usd),2) revenue_usd,SUM(f.target_rx) target_rx,ROUND(100.0*SUM(f.prescriptions)/NULLIF(SUM(f.target_rx),0),2) target_attainment_pct,RANK() OVER(ORDER BY SUM(f.revenue_usd) DESC) revenue_rank,ROUND(100.0*SUM(f.revenue_usd)/NULLIF(SUM(SUM(f.revenue_usd)) OVER(),0),2) revenue_contribution_pct FROM prescription_month f JOIN product p ON p.product_id=f.product_id GROUP BY p.product_id,p.product_name,p.therapy_area;
